<art_studio> ::= <art_piece_list>

<art_piece_list> ::= <art_piece> | <art_piece> <art_piece_list>

<art_piece> ::= <type> <title> <artist> <date> <price> <description>

<type> ::= "Painting" | "Photograph" | "Sculpture" | "Digital" | "Drawing" | "sketch"

<artist> ::= <first_name> <last_name>

<title> ::= <string>

<date> ::= "Created: " <intiger> "Ad" | "created: " <intiger> "Bc"

<price> ::= <intiger> "." <intiger> "€" | <intiger> "." <intiger> "$"

<description> ::= <string>

<first_name> ::= <string>

<last_name> ::= <string>

<string> ::= <letter> | <letter> <string>

<intiger> ::= <number> | <number> <intiger>

<letter> ::= "A" | "B" | "C" | "D" | "E" | "F" | "G" | "H" | "I" | "J" | "K" | "L" | "M" | "N" | "O" | "P" | "Q" | "R" | "S" | "T" | "U" | "V" | "W" | "X" | "Y" | "Z" | "a" | "b" | "c" | "d" | "e" | "f" | "g" | "h" | "i" | "j" | "k" | "l" | "m" | "n" | "o" | "p" | "q" | "r" | "s" | "t" | "u" | "v" | "w" | "x" | "y" | "z"

<number> ::= "0" | "1" | "2" | "3" | "4" | "5" | "6" | "7" | "8" | "9" 