name:                fp2024
version:             0.1.0.0
github:              "githubuser/fp2024"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/fp2024#readme>

dependencies:
- base >= 4.7 && < 5
- free
- random
- stm
- async
- QuickCheck
- transformers
- strict
- lens
- wreq
- bytestring
- string-conversions
- scotty
- mtl

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -threaded
- -rtsopts
- -with-rtsopts=-N

library:
  source-dirs: src
  dependencies:
  - free
  - random
  - stm
  - async
  - QuickCheck
  - transformers
  - strict
  - mtl
  - deepseq


executables:
  fp2024-one:
    main:                Main.hs
    source-dirs:         app1
    dependencies:
    - fp2024
    - repline
    - mtl
  fp2024-two:
    main:                Main.hs
    source-dirs:         app2
    dependencies:
    - fp2024
    - repline
    - mtl
  fp2024-three:
    main:                Main.hs
    source-dirs:         app3
    dependencies:
    - fp2024
    - repline
    - mtl
    - stm
  fp2024-four-client:
    main:                Main.hs
    source-dirs:         app4-client
    dependencies:
    - fp2024
    - repline
    - lens
    - wreq
    - bytestring
    - string-conversions
    - mtl
  fp2024-four-server:
    main:                Main.hs
    source-dirs:         app4-server
    dependencies:
    - fp2024
    - repline
    - scotty
    - string-conversions
    - stm
    - mtl

tests:
  fp2024-test:
    main:                Spec.hs
    source-dirs:         
    - test
    - src
    dependencies:
    - fp2024
    - tasty
    - tasty-hunit
    - tasty-quickcheck
    - QuickCheck
    - mtl
  fp2024-doctest:
    main:                Doctest.hs
    source-dirs:         doctest
    dependencies:
    - doctest
    - mtl
